spring:
  application:
    name: Flyway Migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:mydb}
    username: ${DATABASE_USER:myuser}
    password: ${DATABASE_PASSWORD:mypassword}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect